name: Created To Create
favicon: null
layout_spectrum: 0.9273251318372786
typography_spectrum: 0.030333941569551826
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#b20405'
    - '#fea204'
    - '#fe4d01'
  brandStrength: 0.5
  lightness: 0.8661932724062353
  saturation: 0.7933078135829419
  rhythmicContrast: 0.5
purpose: []
