name: Created To Create
favicon: null
layout_spectrum: 0.49994
typography_spectrum: 0.26572
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2f5b0b'
    - '#d1e2d1'
    - '#5d8f1b'
    - '#9fc72a'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
