name: Created To Create
favicon: null
layout_spectrum: 0.9273251318372786
typography_spectrum: 0.030333941569551826
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2815610410179943
  lightness: 0.8661932724062353
  saturation: 0.7933078135829419
  rhythmicContrast: 0.2936073928140104
purpose: []
